<a href="https://colab.research.google.com/github/alfonsocude/MACHINE-LEARNING-1/blob/main/04%20-%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Recuerda que una vez abierto, Da clic en "Copiar en Drive", de lo contrario no podras alamancenar tu progreso**

Nota: no olvide ir ejecutando las celdas de código de arriba hacia abajo para que no tenga errores de importación de librerías o por falta de definición de variables.

# **Numpy** 

Esta biblioteca, cuyo nombre significa numerical Python, constituye el núcleo de muchas otras bibliotecas de Python que se han originado a partir de ella. De hecho, NumPy es la biblioteca básica para la computación científica en Python, ya que proporciona estructuras de datos y funciones de alto rendimiento que el paquete básico de Python no proporciona.

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

## Importar la libreria NumPy

In [4]:
import numpy as np 

In [33]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [34]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [7]:
from math import sin

seno = []
for i in [1,2,3]: 
    seno.append(sin(i))
seno


[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [44]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B= np.matrix([[10,11,12],[13,14,15],[16,17,18]])
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [46]:
a = np.arange(1,10).reshape((3,3))
print(a)
b = np.arange(10,19).reshape((3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [50]:
a * b

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [51]:
b * a

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [52]:
A*B

matrix([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [53]:
B*A

matrix([[138, 171, 204],
        [174, 216, 258],
        [210, 261, 312]])

In [8]:
x = np.array([[1,2,3], [4,5,6]])

In [9]:
y = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

## **Creación intrinseca de arreglos**

La biblioteca NumPy proporciona un conjunto de funciones que generan ndarrays con contenido inicial, creados con diferentes valores según la función.



In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,12,3)

array([0, 3, 6, 9])

## **Operaciones básicas**

In [15]:
a = np.arange(0,4)

## **Matrices vs Arrreglos**


## **Funciones universales**

In [16]:
a = np.arange(1,6)


In [17]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [18]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [19]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

## **Agregar funciones**

In [20]:
a = 5*np.random.random(5)+1

## **Indexando**

In [21]:
a = np.arange(10, 16)

In [22]:
A = np.arange(10,19).reshape((3,3))

In [23]:
A[1,2]

np.int64(15)

## **Slicing**


In [24]:
a = np.arange(10,16)

In [25]:
a[1:4]

array([11, 12, 13])

In [26]:
a[1:5:2]

array([11, 13])

In [27]:
a[::2]

array([10, 12, 14])

In [28]:
a[:5:2]

array([10, 12, 14])

In [29]:
a[:5:]

array([10, 11, 12, 13, 14])

In [30]:
b = np.arange(10,31)

In [31]:
A = np.arange(10,19).reshape((3,3))

## **Condicionales y arreglos Booleanos**

In [32]:
A = np.random.random((4,4))

# **Referencias**

[1]. https://es.wikipedia.org/wiki/NumPy 

[2]. Unpingo J. Python for Probability, Statistics and Machine Learning. Second Edition. Ed. 
Springer.

[3]. Nelli F. Python Data Analytics. With Pandas, NumPy and Matplotlib. Second Ed.