<a href="https://colab.research.google.com/github/alfonsocude/MACHINE-LEARNING-1/blob/main/05-%5BTaller%5D-numpy.ipynb#scrollTo=bm0ko4ipL_Ks" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Recuerda que una vez abierto, Da clic en "Copiar en Drive", de lo contrario no podras alamancenar tu progreso**

Nota: no olvide ir ejecutando las celdas de código de arriba hacia abajo para que no tenga errores de importación de librerías o por falta de definición de variables.

# **Taller Numpy** 



1) Importar la libreria numpy y ver la versión que se está usando

In [19]:
import numpy as np
np.__version__

'2.3.2'

2) Crear un arreglo de tamaño 1D desde 10 hasta 30

In [20]:
D = np.arange(10,31)
print(D)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


3) Crear un arreglo booleano con valor True de tamaño 4x4

In [31]:
matriz = np.ones((4,4), dtype=bool)

print(matriz)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


4) Generar un arreglo desde el 10 hasta el 30, extraer los elementos pares del arreglo generado.

In [22]:
d2 = np.arange(10,31,2)
print(d2)

[10 12 14 16 18 20 22 24 26 28 30]


5) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [23]:
D3 = np.arange(10,31)

for idx, i in enumerate(D3):
    if i % 2 == 0:
        D3[idx] = -1
print(D3)

[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21 -1 23 -1 25 -1 27 -1 29 -1]


6) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [24]:
r = np.arange(10,31)
print
r[r % 2 == 0] = -1
print(r)

[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21 -1 23 -1 25 -1 27 -1 29 -1]


7) Reemplazar todos los números pares por -1 y por 0 los impares de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [25]:
D4 = np.arange(10,31)
print
for j, k in enumerate(D4):
    if k % 2 == 0:
        D4[j] = -1
    else:
        D4[j] = 0
print(D4)

[-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]


8) Reemplazar todos los números pares por -1 y los impares por 0 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [29]:
r1 = np.where(np.arange(10,31) % 2 == 0, -1, 0)

print(r1)

[-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
